/* PocketJS frame loop for ArtInChip luban-lite.
 *
 * One guest runs at a time. Each tick: drain touch contacts, run one
 * guest turn, plan the RGB565 damage, render the damage rectangles straight
 * into the non-scanned aicfb buffer, pan, and wait for the scan to land.
 * The contract macros in pocketjs_aic_contract.h are generated by
 * tools/aic.ts package and pin the guest to the host profile the package was
 * compiled against. */
#include <rtconfig.h>
#include <rtthread.h>

#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <unistd.h>

#include "pocketjs/guest.h"
#include "pocketjs/package.h"
#include "pocketjs/render_rgb565.h"
#include "pocketjs/ui_core.h"
#include "pocketjs/ui_qjs.h"

#include "pocketjs_aic_contract.h"
#include "pocketjs_display.h"
#include "pocketjs_heap.h"
#include "pocketjs_touch.h"
#include "pocketjs_time.h"

#define POCKETJS_TASK_STACK_BYTES (384U * 1024U)
#define POCKETJS_TASK_PRIORITY 20
#define POCKETJS_PACKAGE_BUFFER_MAX (4U * 1024U * 1024U)

struct pocketjs_aic_state {
  struct pocketjs_aic_display *display;
  struct pocketjs_aic_touch *touch;
  pocketjs_guest_t *guest;
  pocketjs_ui_core_t *core;
  pocketjs_ui_qjs_t *binding;
  pocketjs_rgb565_renderer_t *renderer;
  pocketjs_rgb565_target_t *targets[2];
  pocketjs_aic_touch_contact_t contacts[POCKETJS_UI_MAX_TOUCHES];
  uint32_t touch_range_x;
  uint32_t touch_range_y;
  uint32_t buffer_index;
};

/* The package lives either on a filesystem path or linked into the firmware
 * as generated/pocket_bin.c. One host process runs at a time, so the source
 * sits in static storage while the runner task drains it. */
static struct {
  const char *path;
  const uint8_t *embedded;
  size_t embedded_size;
} pocketjs_aic_source;

static int pocketjs_load_package(const char *path, uint8_t **out_bytes,
                                 size_t *out_size) {
  int fd = open(path, O_RDONLY, 0);
  if (fd < 0) {
    rt_kprintf("[PocketJS] package: open %s failed\n", path);
    return -1;
  }
  off_t size = lseek(fd, 0, SEEK_END);
  if (size <= 0 || (size_t)size > POCKETJS_PACKAGE_BUFFER_MAX) {
    rt_kprintf("[PocketJS] package: %s is empty or larger than %u bytes\n",
               path, (unsigned)POCKETJS_PACKAGE_BUFFER_MAX);
    close(fd);
    return -1;
  }
  lseek(fd, 0, SEEK_SET);
  uint8_t *bytes = (uint8_t *)rt_malloc((size_t)size);
  if (bytes == RT_NULL) {
    rt_kprintf("[PocketJS] package: %u bytes of heap unavailable\n", (unsigned)size);
    close(fd);
    return -1;
  }
  size_t read_total = 0U;
  while (read_total < (size_t)size) {
    ssize_t chunk = read(fd, bytes + read_total, (size_t)size - read_total);
    if (chunk <= 0) {
      rt_kprintf("[PocketJS] package: short read at %u\n", (unsigned)read_total);
      rt_free(bytes);
      close(fd);
      return -1;
    }
    read_total += (size_t)chunk;
  }
  close(fd);
  *out_bytes = bytes;
  *out_size = (size_t)size;
  return 0;
}

static void pocketjs_fill_contract(pocketjs_package_host_contract_t *contract) {
  contract->struct_size = sizeof(*contract);
  contract->target_id = POCKETJS_AIC_CONTRACT_TARGET_ID;
  contract->host_abi = POCKETJS_AIC_CONTRACT_HOST_ABI;
  contract->tick_hz = POCKETJS_AIC_CONTRACT_TICK_HZ;
  contract->logical_width = POCKETJS_AIC_CONTRACT_LOGICAL_WIDTH;
  contract->logical_height = POCKETJS_AIC_CONTRACT_LOGICAL_HEIGHT;
  contract->physical_width = POCKETJS_AIC_CONTRACT_PHYSICAL_WIDTH;
  contract->physical_height = POCKETJS_AIC_CONTRACT_PHYSICAL_HEIGHT;
  contract->raster_density = POCKETJS_AIC_CONTRACT_RASTER_DENSITY;
  contract->presentation = POCKETJS_AIC_CONTRACT_PRESENTATION;
  memcpy(contract->profile_hash, pocketjs_aic_contract_profile_hash,
         POCKETJS_PACKAGE_HASH_BYTES);
}

static void pocketjs_print_stats(uint32_t frames_in_second,
                                 pocketjs_rgb565_render_stats_t *stats,
                                 const pocketjs_guest_stats_t *guest_stats) {
  rt_kprintf("[PocketJS] fps=%u damage=%u px=%u full=%u js_heap=%u/%u\n",
             (unsigned)frames_in_second,
             (unsigned)stats->damage_regions,
             (unsigned)stats->damage_pixels,
             (unsigned)stats->full_redraw,
             guest_stats != RT_NULL ? (unsigned)guest_stats->heap_used : 0U,
             guest_stats != RT_NULL ? (unsigned)guest_stats->heap_limit : 0U);
}

static void pocketjs_aic_task(void *opaque) {
  struct pocketjs_aic_state state;
  uint8_t *package_bytes = RT_NULL;
  const uint8_t *package_data = RT_NULL;
  size_t package_size = 0U;
  pocketjs_package_t *package = RT_NULL;
  int exit_code = 0;

  rt_memset(&state, 0, sizeof(state));

  state.display = pocketjs_aic_display_open();
  if (state.display == RT_NULL) {
    exit_code = -1;
    goto cleanup;
  }
  pocketjs_aic_display_info_t display_info;
  if (!pocketjs_aic_display_info(state.display, &display_info)) {
    rt_kprintf("[PocketJS] display: no double-buffered framebuffer\n");
    exit_code = -1;
    goto cleanup;
  }
  if (display_info.width != POCKETJS_AIC_CONTRACT_PHYSICAL_WIDTH ||
      display_info.height != POCKETJS_AIC_CONTRACT_PHYSICAL_HEIGHT) {
    rt_kprintf("[PocketJS] display: panel %ux%u differs from the contract\n",
               (unsigned)display_info.width, (unsigned)display_info.height);
    exit_code = -1;
    goto cleanup;
  }
  if (display_info.stride_bytes != (uint32_t)display_info.width * 2U) {
    rt_kprintf("[PocketJS] display: stride %u breaks in-place strips\n",
               (unsigned)display_info.stride_bytes);
    exit_code = -1;
    goto cleanup;
  }

  state.touch = pocketjs_aic_touch_open(AIC_TOUCH_PANEL_NAME);
  pocketjs_aic_touch_range(state.touch, &state.touch_range_x, &state.touch_range_y);

  if (pocketjs_aic_source.path != RT_NULL) {
    if (pocketjs_load_package(pocketjs_aic_source.path, &package_bytes,
                              &package_size) != 0) {
      exit_code = -1;
      goto cleanup;
    }
    package_data = package_bytes;
  } else if (pocketjs_aic_source.embedded != RT_NULL &&
             pocketjs_aic_source.embedded_size > 0U &&
             pocketjs_aic_source.embedded_size <= POCKETJS_PACKAGE_BUFFER_MAX) {
    /* The embedded array sits in flash-backed rodata and the package parser
     * treats the buffer as read-only, so no copy is needed. */
    package_data = pocketjs_aic_source.embedded;
    package_size = pocketjs_aic_source.embedded_size;
  } else {
    rt_kprintf("[PocketJS] package: no source; run pocketjs_aic_run or "
               "pocketjs_aic_run_embedded first\n");
    exit_code = -1;
    goto cleanup;
  }
  if (pocketjs_package_open(package_data, package_size, 0, &package) != ESP_OK) {
    rt_kprintf("[PocketJS] package: parse failed\n");
    exit_code = -1;
    goto cleanup;
  }
  pocketjs_package_host_contract_t contract;
  pocketjs_fill_contract(&contract);
  pocketjs_package_variant_t variant;
  variant.struct_size = sizeof(variant);
  if (pocketjs_package_select(package, &contract, &variant) != ESP_OK) {
    rt_kprintf("[PocketJS] package: no %s variant matches this firmware; "
               "rebuild the package with tools/aic.ts\n",
               POCKETJS_AIC_CONTRACT_TARGET_ID);
    exit_code = -1;
    goto cleanup;
  }

  pocketjs_guest_config_t guest_config;
  pocketjs_guest_config_defaults(&guest_config);
  guest_config.stack_limit = 256U * 1024U;
  /* The adaptive trigger (live + 50%) fires stop-the-world collections every
   * few frames on this PSRAM-resident heap; a fixed high threshold keeps the
   * collections rare, and the idle-frame pass below keeps the peak bounded. */
  guest_config.gc_threshold = 3U * 1024U * 1024U;
  if (pocketjs_guest_create(&guest_config, &state.guest) != ESP_OK) {
    rt_kprintf("[PocketJS] guest: create failed\n");
    exit_code = -1;
    goto cleanup;
  }

  pocketjs_ui_core_config_t core_config;
  pocketjs_ui_core_config_defaults(&core_config);
  core_config.logical_width = POCKETJS_AIC_CONTRACT_LOGICAL_WIDTH;
  core_config.logical_height = POCKETJS_AIC_CONTRACT_LOGICAL_HEIGHT;
  core_config.raster_density = POCKETJS_AIC_CONTRACT_RASTER_DENSITY;
  core_config.tick_hz = POCKETJS_AIC_CONTRACT_TICK_HZ;
  if (pocketjs_ui_core_create(&core_config, &state.core) != ESP_OK) {
    rt_kprintf("[PocketJS] core: create failed\n");
    exit_code = -1;
    goto cleanup;
  }

  pocketjs_ui_qjs_config_t binding_config = {
      .struct_size = sizeof(binding_config),
      .target_id = POCKETJS_AIC_CONTRACT_TARGET_ID,
      .host_abi = POCKETJS_AIC_CONTRACT_HOST_ABI,
  };
  if (pocketjs_ui_qjs_create(state.guest, state.core, &binding_config,
                             &state.binding) != ESP_OK) {
    rt_kprintf("[PocketJS] binding: create failed\n");
    exit_code = -1;
    goto cleanup;
  }
  if (pocketjs_ui_qjs_feed_pak(state.binding, variant.pak.data, variant.pak.size) != ESP_OK ||
      pocketjs_ui_qjs_mount(state.binding) != ESP_OK) {
    rt_kprintf("[PocketJS] binding: pak/mount failed\n");
    exit_code = -1;
    goto cleanup;
  }
  if (pocketjs_guest_eval(state.guest, (const char *)variant.javascript.data,
                          variant.javascript.size - 1U,
                          POCKETJS_AIC_CONTRACT_TARGET_ID) != ESP_OK) {
    rt_kprintf("[PocketJS] guest: bundle eval failed\n");
    exit_code = -1;
    goto cleanup;
  }

  pocketjs_rgb565_renderer_config_t renderer_config;
  pocketjs_rgb565_renderer_config_defaults(&renderer_config);
  renderer_config.scale = POCKETJS_AIC_CONTRACT_RASTER_DENSITY;
  if (pocketjs_rgb565_renderer_create(&renderer_config, &state.renderer) != ESP_OK ||
      pocketjs_rgb565_target_create(&state.targets[0]) != ESP_OK ||
      pocketjs_rgb565_target_create(&state.targets[1]) != ESP_OK) {
    rt_kprintf("[PocketJS] renderer: create failed\n");
    exit_code = -1;
    goto cleanup;
  }

  /* Both scan buffers start cleared so the first pan never shows garbage. */
  rt_memset(display_info.buffers[0], 0, display_info.buffer_size);
  rt_memset(display_info.buffers[1], 0, display_info.buffer_size);

  const uint32_t tick_hz = POCKETJS_AIC_CONTRACT_TICK_HZ;
  const rt_tick_t frame_ticks = rt_tick_from_millisecond(1000U / tick_hz);
  rt_tick_t next_frame = rt_tick_get();
  uint32_t frames = 0U;
  rt_tick_t stats_deadline = rt_tick_get() + rt_tick_from_millisecond(1000U);
  uint32_t touch_reports = 0U;
  rt_tick_t gc_deadline = rt_tick_get() + rt_tick_from_millisecond(2000U);
  pocketjs_rgb565_render_stats_t second_stats;
  rt_memset(&second_stats, 0, sizeof(second_stats));
  second_stats.struct_size = sizeof(second_stats);
  rt_tick_t turn_ticks_max = 0U;
  rt_tick_t calib_deadline = rt_tick_get();

  while (1) {
    if (pocketjs_aic_tick_reached(rt_tick_get(), next_frame)) {
      next_frame += frame_ticks;
    }

    pocketjs_ui_input_t input;
    rt_memset(&input, 0, sizeof(input));
    input.struct_size = sizeof(input);
    pocketjs_ui_touch_t touches[POCKETJS_UI_MAX_TOUCHES];
    size_t touch_count = 0U;
    if (state.touch != RT_NULL) {
      rt_size_t count = pocketjs_aic_touch_sample(
          state.touch, state.contacts, POCKETJS_UI_MAX_TOUCHES);
      for (rt_size_t index = 0;
           index < count && touch_count < POCKETJS_UI_MAX_TOUCHES; index++) {
        uint32_t x = (uint32_t)state.contacts[index].x *
                     POCKETJS_AIC_CONTRACT_LOGICAL_WIDTH / state.touch_range_x;
        uint32_t y = (uint32_t)state.contacts[index].y *
                     POCKETJS_AIC_CONTRACT_LOGICAL_HEIGHT / state.touch_range_y;
        if (x >= POCKETJS_AIC_CONTRACT_LOGICAL_WIDTH) {
          x = POCKETJS_AIC_CONTRACT_LOGICAL_WIDTH - 1U;
        }
        if (y >= POCKETJS_AIC_CONTRACT_LOGICAL_HEIGHT) {
          y = POCKETJS_AIC_CONTRACT_LOGICAL_HEIGHT - 1U;
        }
        if (pocketjs_aic_tick_reached(rt_tick_get(), calib_deadline)) {
          /* Once per second: raw panel coordinates next to the mapped
           * viewport point, so a flipped axis is obvious on the log. */
          rt_kprintf("[PocketJS] touch raw=(%u,%u) range=(%u,%u) mapped=(%u,%u)\n",
                     (unsigned)state.contacts[index].x,
                     (unsigned)state.contacts[index].y,
                     (unsigned)state.touch_range_x,
                     (unsigned)state.touch_range_y,
                     (unsigned)x, (unsigned)y);
          calib_deadline = rt_tick_get() + rt_tick_from_millisecond(1000U);
        }
        touches[touch_count].id = state.contacts[index].id;
        touches[touch_count].x = (uint16_t)x;
        touches[touch_count].y = (uint16_t)y;
        touch_count++;
      }
    }
    input.touches = touches;
    input.touch_count = touch_count;

    pocketjs_ui_frame_view_t frame;
    rt_memset(&frame, 0, sizeof(frame));
    frame.struct_size = sizeof(frame);
    const rt_tick_t turn_started = rt_tick_get();
    esp_err_t turn = pocketjs_ui_turn(state.binding, &input, &frame);
    const rt_tick_t turn_ticks = rt_tick_get() - turn_started;
    if (turn_ticks > turn_ticks_max) {
      turn_ticks_max = turn_ticks;
    }
    if (turn != ESP_OK) {
      rt_kprintf("[PocketJS] guest: turn failed (%d), stopping\n", (int)turn);
      pocketjs_guest_stats_t failed_stats = {.struct_size = sizeof(failed_stats)};
      pocketjs_guest_stats(state.guest, &failed_stats);
      rt_kprintf("[PocketJS] frames=%u errors=%u touches=%u tick=%u\n",
                 (unsigned)failed_stats.frames, (unsigned)failed_stats.frame_errors,
                 (unsigned)touch_count, (unsigned)rt_tick_get());
      rt_size_t pool_total = 0U, pool_used = 0U, pool_max = 0U;
      pocketjs_heap_stats(&pool_total, &pool_used, &pool_max);
      rt_kprintf("[PocketJS] js_heap=%u/%u js_pool=%u/%u max=%u\n",
                 (unsigned)failed_stats.heap_used, (unsigned)failed_stats.heap_limit,
                 (unsigned)pool_used, (unsigned)pool_total, (unsigned)pool_max);
      exit_code = -1;
      break;
    }

    uint32_t index = state.buffer_index ^ 1U;
    uint8_t *buffer = display_info.buffers[index];
    pocketjs_rgb565_target_t *target = state.targets[index];
    pocketjs_rgb565_damage_plan_t plan;
    plan.struct_size = sizeof(plan);
    pocketjs_rgb565_render_stats_t frame_stats;
    rt_memset(&frame_stats, 0, sizeof(frame_stats));
    frame_stats.struct_size = sizeof(frame_stats);
    if (pocketjs_rgb565_prepare(state.renderer, target, &frame, &plan) == ESP_OK) {
      esp_err_t render = ESP_OK;
      for (uint32_t region_index = 0U;
           region_index < plan.region_count && render == ESP_OK; region_index++) {
        const pocketjs_rgb565_rect_t region = plan.regions[region_index];
        uint16_t *strip = (uint16_t *)(buffer + (size_t)region.y * display_info.stride_bytes);
        size_t strip_pixels = (size_t)display_info.width * region.height;
        pocketjs_rgb565_render_stats_t region_stats;
        rt_memset(&region_stats, 0, sizeof(region_stats));
        region_stats.struct_size = sizeof(region_stats);
        render = pocketjs_rgb565_render_strip(state.renderer, &frame, strip,
                                              strip_pixels, region, RT_NULL,
                                              &region_stats);
        frame_stats.software_ops += region_stats.software_ops;
        frame_stats.software_words += region_stats.software_words;
        frame_stats.damage_pixels += region_stats.damage_pixels;
        frame_stats.full_redraw |= region_stats.full_redraw;
      }
      frame_stats.damage_regions = plan.region_count;
      if (render == ESP_OK) {
        render = pocketjs_rgb565_commit(state.renderer, target, &frame);
      }
      if (render != ESP_OK) {
        rt_kprintf("[PocketJS] render: failed (%d)\n", (int)render);
      } else {
        pocketjs_aic_display_present(state.display, index);
        state.buffer_index = index;
        pocketjs_aic_display_wait_vsync(state.display);
      }
    } else {
      rt_kprintf("[PocketJS] render: prepare failed\n");
    }

    frames++;
    second_stats.software_ops += frame_stats.software_ops;
    second_stats.software_words += frame_stats.software_words;
    second_stats.damage_pixels += frame_stats.damage_pixels;
    second_stats.damage_regions += frame_stats.damage_regions;
    second_stats.full_redraw |= frame_stats.full_redraw;
    if (frame_stats.damage_regions == 0U) {
      /* The frame did no visible work, so pay the collection cost here
       * instead of letting the adaptive trigger stop a busy frame. */
      if (pocketjs_aic_tick_reached(rt_tick_get(), gc_deadline)) {
        pocketjs_guest_run_gc(state.guest);
        gc_deadline = rt_tick_get() + rt_tick_from_millisecond(2000U);
      }
    }
    if (pocketjs_aic_tick_reached(rt_tick_get(), stats_deadline)) {
      stats_deadline += rt_tick_from_millisecond(1000U);
      pocketjs_guest_stats_t guest_stats;
      rt_memset(&guest_stats, 0, sizeof(guest_stats));
      guest_stats.struct_size = sizeof(guest_stats);
      const pocketjs_guest_stats_t *guest_stats_pointer =
          pocketjs_guest_stats(state.guest, &guest_stats) == ESP_OK ? &guest_stats : RT_NULL;
      pocketjs_print_stats(frames, &second_stats, guest_stats_pointer);
      rt_memset(&second_stats, 0, sizeof(second_stats));
      second_stats.struct_size = sizeof(second_stats);
      rt_size_t pool_total = 0U, pool_used = 0U, pool_max = 0U;
      pocketjs_heap_stats(&pool_total, &pool_used, &pool_max);
      const uint32_t reports = pocketjs_aic_touch_report_count(state.touch);
      rt_kprintf("[PocketJS] turn_max=%u ms touch_reports=%u "
                 "js_pool=%u/%u max=%u\n",
                 (unsigned)(turn_ticks_max * 1000U / RT_TICK_PER_SECOND),
                 (unsigned)(reports - touch_reports),
                 (unsigned)pool_used, (unsigned)pool_total,
                 (unsigned)pool_max);
      frames = 0U;
      touch_reports = reports;
      turn_ticks_max = 0U;
    }

    const rt_tick_t wait = pocketjs_aic_ticks_until(rt_tick_get(), next_frame);
    if (wait != 0U) {
      rt_thread_delay(wait);
    } else {
      rt_thread_yield();
    }
  }

cleanup:
  if (state.touch != RT_NULL) {
    pocketjs_aic_touch_close(state.touch);
  }
  if (state.targets[1] != RT_NULL) {
    pocketjs_rgb565_target_destroy(state.targets[1]);
  }
  if (state.targets[0] != RT_NULL) {
    pocketjs_rgb565_target_destroy(state.targets[0]);
  }
  if (state.renderer != RT_NULL) {
    pocketjs_rgb565_renderer_destroy(state.renderer);
  }
  if (state.binding != RT_NULL) {
    pocketjs_ui_qjs_destroy(state.binding);
  }
  if (state.guest != RT_NULL) {
    pocketjs_guest_destroy(state.guest);
  }
  if (state.core != RT_NULL) {
    pocketjs_ui_core_destroy(state.core);
  }
  if (package != RT_NULL) {
    pocketjs_package_close(package);
  }
  if (package_bytes != RT_NULL) {
    rt_free(package_bytes);
  }
  pocketjs_aic_display_close(state.display);
  rt_kprintf("[PocketJS] run finished with code %d\n", exit_code);
}

static int pocketjs_aic_start(void) {
  pocketjs_heap_init();
  rt_thread_t task = rt_thread_create("pocketjs", pocketjs_aic_task, RT_NULL,
                                      POCKETJS_TASK_STACK_BYTES,
                                      POCKETJS_TASK_PRIORITY, 10U);
  if (task == RT_NULL) {
    rt_kprintf("[PocketJS] task: create failed\n");
    return -1;
  }
  rt_thread_startup(task);
  return 0;
}

int pocketjs_aic_run(const char *package_path) {
  pocketjs_aic_source.path = package_path;
  pocketjs_aic_source.embedded = RT_NULL;
  pocketjs_aic_source.embedded_size = 0U;
  return pocketjs_aic_start();
}

int pocketjs_aic_run_embedded(const uint8_t *bytes, size_t size) {
  pocketjs_aic_source.path = RT_NULL;
  pocketjs_aic_source.embedded = bytes;
  pocketjs_aic_source.embedded_size = size;
  return pocketjs_aic_start();
}
