#!/usr/bin/env bun
// ArtInChip luban-lite packaging and build driver.
//
//   bun tools/aic.ts package [--example hosts/aic/examples/demo68] [--luban <sdk>]
//   bun tools/aic.ts build   [--luban <sdk>] [--defconfig <name>] [-- scons args]
//
// `package` compiles the guest with the PocketJS CLI, writes the host
// contract header the firmware compiles in, and emits the package as a C
// array (generated/pocket_bin.c) that links into the firmware image.
// `build` runs the SDK build with POCKETJS_ROOT pointing at this checkout.

import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import {
  hashPocketAicHostProfile,
  validatePocketAicHostProfile,
  type PocketAicHostProfile,
} from "../framework/src/manifest/aic-host.ts";
import { canonicalJson } from "../framework/src/manifest/plan.ts";

const ROOT = new URL("..", import.meta.url).pathname;
const DEFAULT_LUBAN_ROOT = "/Volumes/aigo_1t/DevPkgs/artinchip/luban-lite-m";
const DEFAULT_EXAMPLE = "hosts/aic/examples/demo68";

function usage(message?: string): never {
  if (message) console.error(`aic: ${message}`);
  console.error(
    "usage:\n" +
      "  bun tools/aic.ts package [--example <dir>] [--luban <sdk>]\n" +
      "  bun tools/aic.ts build [--luban <sdk>] [--defconfig <name>] [-- <scons args>]",
  );
  process.exit(1);
}

function takeOption(argv: string[], name: string): string | undefined {
  const index = argv.indexOf(`--${name}`);
  if (index < 0) return undefined;
  const value = argv[index + 1];
  if (!value || value.startsWith("--")) usage(`--${name} requires a value`);
  argv.splice(index, 2);
  return value;
}

async function run(args: string[], cwd: string, env?: Record<string, string>): Promise<void> {
  const child = Bun.spawn(args, {
    cwd,
    stdout: "inherit",
    stderr: "inherit",
    ...(env ? { env: { ...process.env, ...env } } : {}),
  });
  const status = await child.exited;
  if (status !== 0) throw new Error(`aic: ${args[0]} failed with exit ${status}`);
}

interface ContractFacts {
  targetId: string;
  hostAbi: number;
  tickHz: number;
  logicalWidth: number;
  logicalHeight: number;
  physicalWidth: number;
  physicalHeight: number;
  rasterDensity: number;
  presentation: number;
  profileHashBytes: string;
}

/** The C `pocketjs_presentation_t` order in package.h. */
const PRESENTATION_VALUES: Record<string, number> = {
  fill: 0,
  fit: 1,
  "integer-fit": 2,
  native: 3,
  stretch: 4,
};

function contractFacts(profile: PocketAicHostProfile): ContractFacts {
  const hashHex = hashPocketAicHostProfile(profile).replace(/^sha256:/, "");
  const presentation = profile.display.presentations[0];
  if (!(presentation in PRESENTATION_VALUES)) {
    usage(`presentation ${presentation} has no C value`);
  }
  return {
    targetId: profile.id,
    hostAbi: 1,
    tickHz: profile.tickHz,
    logicalWidth: profile.display.logicalViewports[0][0],
    logicalHeight: profile.display.logicalViewports[0][1],
    physicalWidth: profile.display.physicalViewport[0],
    physicalHeight: profile.display.physicalViewport[1],
    rasterDensity: profile.display.rasterDensity,
    presentation: PRESENTATION_VALUES[presentation],
    profileHashBytes: hashHex,
  };
}

function contractHeader(facts: ContractFacts): string {
  const hashBytes = facts.profileHashBytes.match(/.{2}/g) ?? [];
  const bytes = hashBytes.map((byte) => `0x${byte}`).join(", ");
  return `/* Generated by tools/aic.ts package from ${"pocket.host.json"}. Do not edit. */
#ifndef POCKETJS_AIC_CONTRACT_H
#define POCKETJS_AIC_CONTRACT_H

#include <stdint.h>

#define POCKETJS_AIC_CONTRACT_TARGET_ID "${facts.targetId}"
#define POCKETJS_AIC_CONTRACT_HOST_ABI ${facts.hostAbi}
#define POCKETJS_AIC_CONTRACT_TICK_HZ ${facts.tickHz}
#define POCKETJS_AIC_CONTRACT_LOGICAL_WIDTH ${facts.logicalWidth}
#define POCKETJS_AIC_CONTRACT_LOGICAL_HEIGHT ${facts.logicalHeight}
#define POCKETJS_AIC_CONTRACT_PHYSICAL_WIDTH ${facts.physicalWidth}
#define POCKETJS_AIC_CONTRACT_PHYSICAL_HEIGHT ${facts.physicalHeight}
#define POCKETJS_AIC_CONTRACT_RASTER_DENSITY ${facts.rasterDensity}
#define POCKETJS_AIC_CONTRACT_PRESENTATION ${facts.presentation}

/* sha256 over the canonical JSON of the host profile. */
static const uint8_t pocketjs_aic_contract_profile_hash[32] = {
  ${bytes}
};

#endif /* POCKETJS_AIC_CONTRACT_H */
`;
}

async function packageCommand(argv: string[]): Promise<void> {
  const exampleRel = takeOption(argv, "example") ?? DEFAULT_EXAMPLE;
  const lubanRoot = resolve(takeOption(argv, "luban") ?? DEFAULT_LUBAN_ROOT);
  if (argv.length > 0) usage(`unknown option ${argv[0]}`);

  const example = resolve(ROOT, exampleRel);
  const manifest = join(example, "pocket.json");
  const hostProfilePath = join(example, "pocket.host.json");
  const profileInput: unknown = await Bun.file(hostProfilePath).json();
  const validated = validatePocketAicHostProfile(profileInput);
  if (!validated.ok) {
    for (const diagnostic of validated.diagnostics) {
      console.error(`${diagnostic.code} ${diagnostic.path || "/"}: ${diagnostic.message}`);
    }
    process.exit(1);
  }
  const profile = validated.value;
  const canonical = canonicalJson(profile);
  const facts = contractFacts(JSON.parse(canonical) as PocketAicHostProfile);

  const buildDir = join(ROOT, ".pocket-build", "aic", profile.id);
  const output = join(buildDir, `${profile.id}.pocket`);
  await run(
    [
      process.execPath,
      join(ROOT, "tools", "pocket.ts"),
      "build",
      "--manifest", manifest,
      "--host-profile", hostProfilePath,
      "--project-root", example,
      "--outdir", join(buildDir, "out"),
      "--plan-dir", join(buildDir, "plans"),
      "--output", output,
    ],
    ROOT,
  );

  const generatedDir = join(ROOT, "hosts", "aic", "generated");
  mkdirSync(generatedDir, { recursive: true });
  writeFileSync(join(generatedDir, "pocketjs_aic_contract.h"), contractHeader(facts));

  // The package links into the firmware image: hosts/aic/SConscript compiles
  // pocket_bin.c, and the port reads the array straight from rodata.
  const bytes = readFileSync(output);
  const lines: string[] = [];
  for (let offset = 0; offset < bytes.length; offset += 16) {
    const row: string[] = [];
    for (const byte of bytes.subarray(offset, offset + 16)) {
      row.push(`0x${byte.toString(16).padStart(2, "0")}`);
    }
    lines.push(`  ${row.join(", ")},`);
  }
  writeFileSync(
    join(generatedDir, "pocket_bin.c"),
    `/* Generated by tools/aic.ts package from ${profile.id}.pocket. Do not edit. */
#include <stdint.h>

const uint8_t pocketjs_embedded_package[] = {
${lines.join("\n")}
};

const uint32_t pocketjs_embedded_package_size = sizeof(pocketjs_embedded_package);
`,
  );

  console.log(`aic: package ${output} (${bytes.byteLength}B)`);
  console.log(`aic: contract hosts/aic/generated/pocketjs_aic_contract.h`);
  console.log(`aic: embedded hosts/aic/generated/pocket_bin.c (${bytes.byteLength}B)`);
}

async function buildCommand(argv: string[]): Promise<void> {
  const lubanRoot = resolve(takeOption(argv, "luban") ?? DEFAULT_LUBAN_ROOT);
  const defconfig = takeOption(argv, "defconfig");
  if (argv.length > 0) usage(`unknown option ${argv[0]}`);

  if (defconfig) {
    await run(["scons", `--apply-def=${defconfig}`], lubanRoot);
  }
  await run(["scons", "-j8"], lubanRoot, { POCKETJS_ROOT: ROOT });
}

const argv = Bun.argv.slice(2);
const command = argv.shift();
try {
  if (command === "package") await packageCommand(argv);
  else if (command === "build") await buildCommand(argv);
  else usage(command ? `unknown command ${command}` : "a command is required");
} catch (error) {
  console.error(error instanceof Error ? error.message : String(error));
  process.exit(1);
}
